### PR TITLE
Add react-css-modules

### LINKED ISSUE #21: Add support to css-modules

### PR DESCRIPTION
**Pull request by gneutzling**
Closes #21

### CODE REVIEW

**Comment by noxan** [comment]
Released as `1.0.14-css-modules`. So we can experiment with this and take a decision then.

**Comment by gneutzling** [comment]
Now we can use css-modules with stylus.

We need to configure webpack to support imports from node_modules.

**Comment by lhrnd0** [comment]
@gneutzling we can still import Stylus files from node_modules with e.g. `~@picter/atoms/variables.styl`, but now CSS files can't be used with `~`. For example, instead of `~normalize.css/normalize.css` we'll have to use  `normalize.css/normalize.css`.
And `url()` imports inside Stylus will have to lose the tilde as well.


Refer to [436](https://github.com/webpack-contrib/css-loader/issues/436) [589](https://github.com/webpack-contrib/css-loader/issues/589) to see something more explained.

**Comment by noxan** [comment]
I think we can close this meanwhile?

**Comment by lhrnd0** [comment]
Yes @noxan , no need for it anymore

**Pull request closed without merging**
